name: Deploy Blog

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: 'Going to install MDL checker'
        run: gem install mdl

      - name: Install Python dependencies
        run: make install

      - name: Run tests
        run: make test

  build:
    if: github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: make install

      - name: Build and publish the blog
        run: invoke publish
