name: Deploy Blog

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Python dependencies
        run: make install

      - name: Run tests
        run: make test

  build:
    if: github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Clone Pelican dependencies
        run: |
          git clone https://github.com/alexandrevicenzi/Flex themes/Flex
          git clone https://github.com/getpelican/pelican-plugins


      - name: Update Some Flex HTML Files With Mine
        run: cp -r flex_modified/* themes/Flex/templates

      - name: Install Python dependencies
        run: make install

      - name: Build and publish the blog
        run: invoke publish
